### ISSUE TITLE
Sikkerhedsscripts

### ISSUE THREAD

**Issue by NeutraChikara** [OS2borgerPC/os2borgerpc-core-scripts#2]
Vi skal have en måde at identificere sikkerhedsscripts på (med antagelsen om at der vil ligge sikkerhedsscript i core-scripts).
Forslag kan være at enten tilføje en ny parameter til hver script, der med true|false angiver om det er et sikkerhedsscript, eller at have en mappe, som i det foregående script-repository, som hedder sikkerhedsscripts, hvori de placeres.

**Comment by NeutraChikara** [comment]
Når dette er lavet, kan jeg tilpasse logikken der indlæser scripts i admin-site, så sikkerhedsscripts installeres korrekt.

**Comment by agnetemoos** [comment]
Der er jo en katergori, der hedder Sikkerhed. Bruger du `parent` til at bygge mappe-strukturen?
F. eks. her
```
---
title: "Juster adgang til kør prompt (ALT-F2)"
**parent: "Sikkerhed"**
source: scripts/dconf_run_prompt_toggle.sh
parameters:
  - name: "Slå kør prompt fra"
    type: "boolean"
    default: null
    mandatory: false
included_in_image: true
compatibility:  
  - "22.04"
  - "BorgerPC"
included_in_image: true
---
```

**Comment by agnetemoos** [comment]
Jeg forstår nok ikke helt hvad du mener med "så sikkerhedsscripts installeres korrekt."

**Comment by sunekochhansen** [comment]
Hej @agnetemoos,

i adminsite er der forskel på om et script ligger under "Scripts" eller "Sikkerhedsscripts".
![image](https://github.com/user-attachments/assets/0e602386-ef76-4855-b1b5-a9898178bed0)

Forskellen styres af et felt i databasen, is_security, der kan ses som "sikkerhedsscript" i django administrations siden for scripts
![Screenshot from 2024-12-13 14-38-52](https://github.com/user-attachments/assets/38fba50c-4ac8-4667-a938-0aa34232688b)

Jeg har ændret parsning af core-scripts, så man kan angive et valgfrit "metadata" felt i markdown filen, hvor man kan angive 3 specielle metadata om filen, der mapper til ovenstående som har indflydelse på hvordan admin-site enten viser scriptet (security), ikke viser det (skjult) eller kan referere det (via uid)

```
---
title: "Tænd/Sluk tidsplaner - aktiver"
parent: "Sikkerhed"
source: scripts/on_off_schedule_set.sh
parameters:
  - name: "parameter 1"
    type: "int"
    default: null
    mandatory: true
compatibility:
  - "22.04"
  - "BorgerPC"
metadata:
  uid: "wake_plan_set"
  security: false
  hidden: true
---
```
